version: '3'
services:
  adp-backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: adp-backend-dev
    ports:
      - "4000:4000"
    env_file: .env
    volumes:
      - ./src:/app/src
    command: npm run dev